
#ifndef __AVB_IDL__
#define __AVB_IDL__

#include "CommonTypes.idl"

module AvbDefs
{
  /* Enumerated type for generic error codes which may be returned */
  enum ErrorCode
  {
    e_EC_SUCCESS,
    e_EC_INVALID_CLASS_CODE,
    e_EC_INVALID_INSTANCE,
    e_EC_INVALID_SERVICE_CODE,
    e_EC_INVALID_ATTRIBUTE_CODE,
    e_EC_UPDATE_ALREADY_IN_PROGRESS,
    e_EC_UPDATE_NOT_IN_PROGRESS,
    e_EC_CORRUPT_IMAGE,
    e_EC_NOT_EXECUTED,
    e_EC_IMAGE_ALREADY_PRESENT
  };

  /** 
   * Type definition for an Ethernet MAC address
   */
  struct MacAddress
  {
    uint8_t mac[6];
  };

};

#endif // __AVB_IDL__
        
// vi:set ai sw=4 expandtab ts=4:

